name: Build
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install coverage
          pip install pytest
          pip install -r requirements.txt
      - name: Create coverage
        run: |
          coverage run -m pytest *.py
          coverage xml *.py
          cat coverage.xml
        continue-on-error: true
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint -ry >> pylint-report.txt {} \;
          cat pylint-report.txt
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
