name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  python-tests:
    name: PythonTest
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create coverage
        run: |
          coverage run -m pytest *.py
          coverage xml *.py
          cat coverage.xml
        continue-on-error: true
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint -ry >> pylint-report.txt {} \;
          cat pylint-report.txt
      - uses: actions/upload-artifact@master
        with:
          name: coverage-report
          path: |
            coverage.xml
            pylint-report.txt
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Retrieve coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: |
            coverage.xml
            pylint-report.txt
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:                                                                                           
          args: >                                                                                       
            -Dsonar.organization=do-chris                                                               
            -Dsonar.projectKey=do-chris_sonarcloud                                                      
            -Dsonar.python.coverage.reportPaths=coverage.xml                                            
            -Dsonar.sources=.                                                                           
            -Dsonar.verbose=true                                                                        
            -Dsonar.python.pylint.reportPaths=pylint-report.txt   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

